### ISSUE TITLE
erreur Ovh En Mutualisé

### ISSUE THREAD

**Issue by Jagounet** [PascalLG/Nubo#1]
J'ai vu tester ca, 
J'ai donc téléchargé le fichier indiqué (nubo.php) lorsque l'on atteint le fichier on n'a un petit message d'erreur.

> Installation failed because of the following issues:

    A 64-bit version of PHP is required

Je n'y connais rien, mais si je peux apporter ma petite contribution !

**Comment by nicosomb** [comment]
Juste pour info, y'a pas mal de personnes qui attendent le passage des mutualisés chez OVH en 64 bits http://community.ovh.com/t/limitation-du-au-php-compile-en-32bits/5171/16
Je pense que d'aller les contacter pour les pousser à le faire est peut-être une bonne solution.

**Comment by PascalLG** [comment]
Il n'y a pas grand-chose à faire à court terme, hélas. Je vais étudier les conséquences et les risques d'autoriser l'installation sur un serveur 32 bits. En attendant, je rajoute dans la doc qu'il faut un serveur 64 bits dans la liste des prérequis.

**Comment by PascalLG** [comment]
La nouvelle version devrait résoudre le problème. Pour plus de sûreté, je conseille d'utiliser le flag ``--test`` avec la commande ``nubo init`` pour valider que le serveur se comporte correctement. Je ferme le problème.
